### ISSUE TITLE
Dynamic Uber State allocation

### ISSUE THREAD

**Issue by timoschwarzer** [ori-rando/wotw-seedgen#84] opened 2022-06-20 20:37 UTC
Instead of using states in the plando_vars group directly, seedgen should "allocate" these states to headers dynamically to prevent collisions.

Syntax proposal:
 `!!state <name> <type>`

e.g.
`!!state skill_velocities int`

Seedgen would then replace something like `$STATE(skill_velocities)` with the int-state it allocated for this header.

In some cases, state sharing between headers is desired. In such cases the state can be marked as `global`, e.g.:

`!!state skill_velocities int global`

Marking a state as `global` will make seedgen use the same uber state in each header. When there exist multiple declarations of the same global state with different types, seedgen should throw an error.

**Comment by timoschwarzer** [comment] 2022-06-20 20:37
s/state/var/g

**Comment by MunWolf** [comment] 2022-06-20 21:45
Duplicate of #1

**Closed by MunWolf** 2022-06-20 21:45 UTC
